kind: Service
apiVersion: v1
metadata:
  name: my-app-service
  labels:
    app: my-app
spec:
  ports:
  - port: 8080        # service port (what clients use inside cluster)
    targetPort: 5000  # match Flask app inside pods
    nodePort: 30080   # external port via NodePort
  selector:
    app: my-app       # this matches your pod label
  type: LoadBalancer  # can be NodePort/ClusterIP/LoadBalancer
