kind: service 
apiVersion: v1
metadata:
  name: my-app-service
  labels:
    app: my-app
spec:
  ports:
  - port: 8080      # container port exposed by the service
    targetPort: 80   # pods port
    nodePort: 30080
  selector:
    app: my-app  # selector to match pods, apply this service to pods with this label
  type: LoadBalancer  #type of service: ClusterIP, NodePort, LoadBalancer
